# Generated by Django 2.2 on 2021-01-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('number', models.IntegerField()),
                ('marks', models.FloatField()),
                ('place', models.CharField(max_length=50)),
            ],
        ),
    ]
